// NesisAI — Dados mock clínicos

const mockMetrics = [
  {
    label: 'Pacientes Ativos',
    value: '28',
    trend: 'up',
    trendValue: '4',
    trendLabel: 'novos esta semana',
  },
  {
    label: 'Análises Hoje',
    value: '12',
    trend: 'up',
    trendValue: '3',
    trendLabel: 'vs. ontem',
  },
  {
    label: 'Alertas GRAVE',
    value: '5',
    trend: 'down',
    trendValue: '2',
    trendLabel: 'vs. semana passada',
  },
  {
    label: 'Interações Detectadas',
    value: '31',
    trend: 'up',
    trendValue: '8',
    trendLabel: 'esta semana',
  },
];

// Análises/dia — 30 dias
const mockChartSeries = [
  3, 5, 4, 7, 6, 8, 5, 9, 11, 8,
  10, 12, 9, 13, 11, 14, 10, 12, 15, 11,
  13, 16, 12, 14, 17, 13, 15, 18, 14, 12,
];

const mockPatients = [
  {
    id: 'p-001',
    name: 'Maria da Silva Santos',
    age: 68,
    sex: 'F',
    lastConsultation: '21/04/2026',
    severity: 'grave',
    alertCount: 2,
    drugs: ['Warfarina', 'Aspirina', 'Enalapril'],
    status: 'done',
  },
  {
    id: 'p-002',
    name: 'João Carlos Pereira',
    age: 52,
    sex: 'M',
    lastConsultation: '21/04/2026',
    severity: 'moderada',
    alertCount: 1,
    drugs: ['Metformina', 'Captopril', 'Atorvastatina'],
    status: 'done',
  },
  {
    id: 'p-003',
    name: 'Antônio Ferreira Lima',
    age: 75,
    sex: 'M',
    lastConsultation: '20/04/2026',
    severity: 'leve',
    alertCount: 1,
    drugs: ['Atenolol', 'Anlodipino', 'AAS 100mg'],
    status: 'done',
  },
  {
    id: 'p-004',
    name: 'Beatriz Ramos Costa',
    age: 44,
    sex: 'F',
    lastConsultation: '20/04/2026',
    severity: 'moderada',
    alertCount: 1,
    drugs: ['Omeprazol', 'Clopidogrel', 'Sinvastatina'],
    status: 'done',
  },
  {
    id: 'p-005',
    name: 'Eduardo Fonseca Silva',
    age: 61,
    sex: 'M',
    lastConsultation: '19/04/2026',
    severity: 'grave',
    alertCount: 3,
    drugs: ['Amiodarona', 'Digoxina', 'Warfarina', 'Losartana'],
    status: 'done',
  },
  {
    id: 'p-006',
    name: 'Larissa Tavares Nunes',
    age: 37,
    sex: 'F',
    lastConsultation: '19/04/2026',
    severity: 'none',
    alertCount: 0,
    drugs: ['Metformina', 'Glibenclamida'],
    status: 'done',
  },
];

const mockHistory = [
  { id: 'c-001', patient: 'Maria da Silva Santos', date: '21/04/2026 09:12', drugs: 3, alerts: 2, severity: 'grave',    time: '0.38s' },
  { id: 'c-002', patient: 'João Carlos Pereira',    date: '21/04/2026 10:45', drugs: 3, alerts: 1, severity: 'moderada', time: '0.29s' },
  { id: 'c-003', patient: 'Antônio Ferreira Lima',  date: '20/04/2026 08:30', drugs: 3, alerts: 1, severity: 'leve',     time: '0.31s' },
  { id: 'c-004', patient: 'Beatriz Ramos Costa',    date: '20/04/2026 14:18', drugs: 3, alerts: 1, severity: 'moderada', time: '0.27s' },
  { id: 'c-005', patient: 'Eduardo Fonseca Silva',  date: '19/04/2026 11:02', drugs: 4, alerts: 3, severity: 'grave',    time: '0.52s' },
  { id: 'c-006', patient: 'Larissa Tavares Nunes',  date: '19/04/2026 15:44', drugs: 2, alerts: 0, severity: 'none',     time: '0.18s' },
  { id: 'c-007', patient: 'Maria da Silva Santos',  date: '17/04/2026 09:05', drugs: 3, alerts: 1, severity: 'grave',    time: '0.35s' },
  { id: 'c-008', patient: 'João Carlos Pereira',    date: '15/04/2026 10:22', drugs: 2, alerts: 0, severity: 'none',     time: '0.22s' },
  { id: 'c-009', patient: 'Eduardo Fonseca Silva',  date: '14/04/2026 08:57', drugs: 4, alerts: 2, severity: 'grave',    time: '0.48s' },
  { id: 'c-010', patient: 'Beatriz Ramos Costa',    date: '12/04/2026 13:31', drugs: 3, alerts: 1, severity: 'moderada', time: '0.30s' },
  { id: 'c-011', patient: 'Antônio Ferreira Lima',  date: '10/04/2026 09:17', drugs: 3, alerts: 1, severity: 'leve',     time: '0.26s' },
  { id: 'c-012', patient: 'Larissa Tavares Nunes',  date: '08/04/2026 16:10', drugs: 2, alerts: 0, severity: 'none',     time: '0.19s' },
];

const mockAlerts = [
  {
    id: 'a-001',
    patient: 'Eduardo Fonseca Silva',
    drug1: 'Amiodarona',
    drug2: 'Warfarina',
    severity: 'grave',
    score: 0.94,
    mechanism: 'A amiodarona inibe o metabolismo hepático da varfarina via CYP2C9, elevando significativamente o INR e o risco de sangramento grave.',
    recommendation: 'Contraindicado sem monitoramento intensivo. Reduzir dose de varfarina em 30–50% e monitorar INR a cada 3–5 dias.',
    date: '19/04/2026',
  },
  {
    id: 'a-002',
    patient: 'Maria da Silva Santos',
    drug1: 'Warfarina',
    drug2: 'Aspirina',
    severity: 'grave',
    score: 0.91,
    mechanism: 'Potenciação dupla do efeito anticoagulante: inibição da síntese de fatores da coagulação (varfarina) + inibição plaquetária (AAS). Risco elevado de hemorragia.',
    recommendation: 'Evitar uso concomitante. Se necessário, utilizar dose mínima de AAS (≤ 100 mg/dia) com monitoramento frequente de INR.',
    date: '21/04/2026',
  },
  {
    id: 'a-003',
    patient: 'Eduardo Fonseca Silva',
    drug1: 'Amiodarona',
    drug2: 'Digoxina',
    severity: 'grave',
    score: 0.88,
    mechanism: 'A amiodarona inibe a glicoproteína-P e reduz a depuração renal e não-renal da digoxina, podendo elevar os níveis plasmáticos e causar toxicidade digitálica.',
    recommendation: 'Reduzir a dose de digoxina em 50% ao iniciar amiodarona. Monitorar sinais de toxicidade (náusea, bradiarritmia) e dosagem sérica de digoxina.',
    date: '19/04/2026',
  },
  {
    id: 'a-004',
    patient: 'Beatriz Ramos Costa',
    drug1: 'Omeprazol',
    drug2: 'Clopidogrel',
    severity: 'moderada',
    score: 0.67,
    mechanism: 'Omeprazol inibe a CYP2C19, reduzindo a conversão do clopidogrel ao seu metabólito ativo, diminuindo o efeito antiagregante plaquetário.',
    recommendation: 'Preferir pantoprazol ou rabeprazol se proteção gástrica for necessária. Monitorar eventos cardiovasculares.',
    date: '20/04/2026',
  },
  {
    id: 'a-005',
    patient: 'João Carlos Pereira',
    drug1: 'Captopril',
    drug2: 'Atorvastatina',
    severity: 'moderada',
    score: 0.52,
    mechanism: 'Potencial interação farmacodinâmica com risco aumentado de hipotensão, especialmente em pacientes idosos ou com volume reduzido.',
    recommendation: 'Monitorar pressão arterial no início do tratamento combinado. Ajuste posológico pode ser necessário.',
    date: '21/04/2026',
  },
  {
    id: 'a-006',
    patient: 'Eduardo Fonseca Silva',
    drug1: 'Warfarina',
    drug2: 'Losartana',
    severity: 'moderada',
    score: 0.48,
    mechanism: 'A losartana pode inibir parcialmente a CYP2C9, influenciando o metabolismo da varfarina e potencializando o efeito anticoagulante.',
    recommendation: 'Monitorar INR regularmente após início ou ajuste de losartana.',
    date: '19/04/2026',
  },
  {
    id: 'a-007',
    patient: 'Maria da Silva Santos',
    drug1: 'Enalapril',
    drug2: 'Warfarina',
    severity: 'leve',
    score: 0.31,
    mechanism: 'Possível interação com modificação leve dos níveis plasmáticos de varfarina. Evidência clínica limitada.',
    recommendation: 'Monitoramento de rotina do INR é suficiente.',
    date: '21/04/2026',
  },
  {
    id: 'a-008',
    patient: 'Antônio Ferreira Lima',
    drug1: 'Atenolol',
    drug2: 'Anlodipino',
    severity: 'leve',
    score: 0.27,
    mechanism: 'Efeito aditivo na redução da frequência cardíaca e da pressão arterial. Geralmente bem tolerado.',
    recommendation: 'Monitorar frequência cardíaca e pressão arterial na introdução da terapia combinada.',
    date: '20/04/2026',
  },
];

window.NesisMock = {
  metrics: mockMetrics,
  chart: mockChartSeries,
  patients: mockPatients,
  history: mockHistory,
  alerts: mockAlerts,
};
